name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
            ref: master
      - name: Create SSH key
        run: |
            sudo apt-get install -y rsync sshpass
            mkdir -p ~/.ssh/
            echo "${{secrets.SSH_HOST}}" > ~/.ssh/known_hosts
            echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
      -   name: Setup Enviroment
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.2'
      -   name: Deploy
          run: rsync -e 'sshpass -p ${{secrets.SSH_PASSWORD}} ssh' -avzP --exclude=public/photos/* --exclude=storage/framework/* --exclude=.git --delete-after ./ ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:~/www/api.chinchillas-show.com
