name: Build and Deploy
on:
  push:
    branches:
      -   master

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
        with:
            ref: master
      - name: Create SSH key
        run: |
            sudo apt-get install -y rsync sshpass
            mkdir -p ~/.ssh/
            echo "37.140.192.11" > ~/.ssh/known_hosts
            echo -e 'Host *\n\tStrictHostKeyChecking no\n\n' > ~/.ssh/config
      -   name: Setup Enviroment
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.2'
      -   name: Deploy
          run: composer run-script deploy
